// Data Dragon names and icons for the numeric ids a `Build.key` carries.
//
// A `Build` in the aggregate model is ids and numbers: `key: [6672, 3006]` is a
// build, and nothing in the artifact says what those ids are called. This module
// is the site's answer, and it is the only reason a build row can render an
// icon instead of a number. It is read at build time from disk - there is no
// runtime lookup and no request to Riot's CDN for a name.
//
// Two sources, in this order:
//
//   1. the checked-in projection in web/src/data/{items,runes,spells}.json,
//      generated by `npm run data:champions` and committed, which is what makes
//      a build work offline and from a fresh clone;
//   2. the aggregate tree's own static projection
//      (agg/v1/static/<ddragon_version>/{items,runes,summoner-spells}.json),
//      which wins per id when it is there, exactly as the tree's champion
//      projection wins over the checked-in one.
//
// Anything that is neither is a hard build failure rather than a blank cell: a
// game-data file whose shape changed must stop the build, not publish a page
// whose icons silently disappeared.

import { existsSync, readFileSync } from 'node:fs';
import { resolve } from 'node:path';

import { loadStaticItems, loadStaticRunes, loadStaticSummonerSpells } from './artifacts';
import { WEB_ROOT } from './web-root';

/**
 * One lookup entry. The shape is frozen by the design system's `BuildList`
 * (`docs/decisions/ADR-006-component-api-extensions.md`); `icon` is an absolute
 * Data Dragon CDN URL, so a consumer needs no version to build it.
 */
export interface BuildLookupEntry {
  name: string;
  icon: string;
}

/** The frozen `lookup` prop of `BuildList`. */
export interface BuildLookup {
  ddragonVersion: string;
  items: Record<number, BuildLookupEntry>;
  runes: Record<number, BuildLookupEntry>;
  spells: Record<number, BuildLookupEntry>;
}

/** The kinds a build key can be, and the keys of `BuildLookup` that hold them. */
export type BuildKind = 'items' | 'runes' | 'spells';

const CHECKED_IN: Record<BuildKind, string> = {
  items: resolve(WEB_ROOT, 'src', 'data', 'items.json'),
  runes: resolve(WEB_ROOT, 'src', 'data', 'runes.json'),
  spells: resolve(WEB_ROOT, 'src', 'data', 'spells.json'),
};

const REGENERATE = 'Run "npm run data:champions" to regenerate it from Data Dragon.';

/**
 * Reads one keyed projection: `{ "<numeric id>": { name, icon } }`.
 *
 * The file is validated rather than trusted. A missing file, a non-numeric key
 * or an entry without a name and an icon throws here, with the file named, so
 * the failure lands on the file that is wrong.
 */
function readCheckedIn(kind: BuildKind): Map<number, BuildLookupEntry> {
  const absolute = CHECKED_IN[kind];
  if (!existsSync(absolute)) throw new Error(`${absolute} is missing. ${REGENERATE}`);

  let raw: unknown;
  try {
    raw = JSON.parse(readFileSync(absolute, 'utf8'));
  } catch (error) {
    throw new Error(`${absolute} is not valid JSON: ${(error as Error).message}`);
  }
  if (!raw || typeof raw !== 'object' || Array.isArray(raw)) {
    throw new Error(`${absolute} must be an object keyed by numeric Data Dragon id. ${REGENERATE}`);
  }

  const entries = new Map<number, BuildLookupEntry>();
  for (const [key, value] of Object.entries(raw as Record<string, unknown>)) {
    const id = Number.parseInt(key, 10);
    if (!Number.isInteger(id)) {
      throw new Error(`${absolute}: key "${key}" is not a numeric Data Dragon id. ${REGENERATE}`);
    }
    const entry = (value ?? {}) as { name?: unknown; icon?: unknown };
    if (typeof entry.name !== 'string' || entry.name === '' || typeof entry.icon !== 'string' || entry.icon === '') {
      throw new Error(`${absolute}: entry ${key} must be { name, icon }. ${REGENERATE}`);
    }
    entries.set(id, { name: entry.name, icon: entry.icon });
  }
  if (entries.size === 0) throw new Error(`${absolute} has no entries. ${REGENERATE}`);
  return entries;
}

/**
 * The tree's static projection for a kind, as id -> entry. `StaticRune` carries
 * a tree id as well; the lookup has no use for it, so it is dropped rather than
 * carried into a shape that does not declare it.
 */
function fromTree(kind: BuildKind, ddragonVersion: string): Map<number, BuildLookupEntry> {
  const entries = new Map<number, BuildLookupEntry>();
  const add = (rows: { id: number; name: string; icon: string }[] | undefined) => {
    for (const row of rows ?? []) {
      if (Number.isInteger(row.id) && row.name && row.icon) entries.set(row.id, { name: row.name, icon: row.icon });
    }
  };

  if (kind === 'items') add(loadStaticItems(ddragonVersion)?.items);
  else if (kind === 'runes') add(loadStaticRunes(ddragonVersion)?.runes);
  else add(loadStaticSummonerSpells(ddragonVersion)?.spells);

  return entries;
}

function toRecord(checkedIn: Map<number, BuildLookupEntry>, tree: Map<number, BuildLookupEntry>): Record<number, BuildLookupEntry> {
  const record: Record<number, BuildLookupEntry> = {};
  for (const [id, entry] of checkedIn) record[id] = entry;
  for (const [id, entry] of tree) record[id] = entry;
  return record;
}

const cache = new Map<string, BuildLookup>();

/**
 * The lookup for one Data Dragon version.
 *
 * Cached per version: the build renders a page per champion and per role from
 * the same projection, and re-reading and re-validating a 100 kB file hundreds
 * of times would be work with no reader benefit.
 */
export function buildLookup(ddragonVersion: string): BuildLookup {
  const cached = cache.get(ddragonVersion);
  if (cached) return cached;

  const lookup: BuildLookup = {
    ddragonVersion,
    items: toRecord(readCheckedIn('items'), fromTree('items', ddragonVersion)),
    runes: toRecord(readCheckedIn('runes'), fromTree('runes', ddragonVersion)),
    spells: toRecord(readCheckedIn('spells'), fromTree('spells', ddragonVersion)),
  };
  cache.set(ddragonVersion, lookup);
  return lookup;
}

/**
 * One entry, or null when the id is not in the projection. Callers render a
 * missing id as the id itself: an unknown id is a fact about the projection,
 * not a reason to drop the row.
 */
export function lookupEntry(lookup: BuildLookup, kind: BuildKind, id: number): BuildLookupEntry | null {
  return lookup[kind][id] ?? null;
}
