package aggregate

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"math"
	"reflect"
	"sort"
	"strings"
	"time"
)

// A JSON Schema check for the artifacts, driven by the schema document
// internal/aggmodel owns.
//
// Why not a library: the schema that matters here is generated by this project
// (internal/aggmodel.Schema, emitted as web/src/types/agg.schema.json by
// cmd/gen-types), it uses a small and closed set of keywords, and the build's
// dependency budget is spent on the extraction engine rather than on a general
// validator. A keyword the validator does not implement is a hard error rather
// than a silent pass, so this can never quietly accept a document it does not
// understand - which is the only failure mode that would make the check
// worthless.
//
// Validation runs on the decoded JSON, not on the typed struct: a struct round
// trip cannot notice an unknown field or a null where a value belongs, and those
// are exactly the contract breaks a reader would hit first.

// supportedKeywords is the closed set of JSON Schema keywords the artifacts use.
var supportedKeywords = map[string]bool{
	"$schema":              true,
	"$id":                  true,
	"$ref":                 true,
	"$defs":                true,
	"title":                true,
	"description":          true,
	"type":                 true,
	"enum":                 true,
	"oneOf":                true,
	"anyOf":                true,
	"allOf":                true,
	"properties":           true,
	"required":             true,
	"additionalProperties": true,
	"items":                true,
	"format":               true,
	"minimum":              true,
	"maximum":              true,
	"minItems":             true,
	"maxItems":             true,
}

// schemaValidator validates documents against one schema document.
type schemaValidator struct {
	defs map[string]any
}

// newSchemaValidator builds a validator from a decoded schema document.
func newSchemaValidator(schema map[string]any) (*schemaValidator, error) {
	raw, ok := schema["$defs"]
	if !ok {
		return nil, errors.New("schema has no $defs object")
	}
	defs, ok := raw.(map[string]any)
	if !ok {
		return nil, errors.New("schema $defs is not an object")
	}
	if len(defs) == 0 {
		return nil, errors.New("schema $defs is empty")
	}
	return &schemaValidator{defs: defs}, nil
}

// schemaFromJSON decodes a schema document. It exists so the verifier can check
// a tree against the schema file that is checked into the repository, which is
// the artifact a reader actually consumes.
func schemaFromJSON(raw []byte) (*schemaValidator, error) {
	decoder := json.NewDecoder(bytes.NewReader(raw))
	decoder.UseNumber()
	var doc map[string]any
	if err := decoder.Decode(&doc); err != nil {
		return nil, fmt.Errorf("decode schema: %w", err)
	}
	return newSchemaValidator(doc)
}

// Validate checks a document against one named definition.
func (v *schemaValidator) Validate(name string, document []byte) error {
	decoder := json.NewDecoder(bytes.NewReader(document))
	decoder.UseNumber()
	var value any
	if err := decoder.Decode(&value); err != nil {
		return fmt.Errorf("%s: not valid JSON: %w", name, err)
	}
	definition, ok := v.defs[name]
	if !ok {
		return fmt.Errorf("schema has no definition %q", name)
	}
	var problems []string
	v.validate(definition, value, name, &problems)
	if len(problems) > 0 {
		return fmt.Errorf("%s does not match the schema:\n    %s", name, strings.Join(problems, "\n    "))
	}
	return nil
}

// Definitions lists the definition names, for a test that wants to know what it
// can validate against.
func (v *schemaValidator) Definitions() []string {
	names := make([]string, 0, len(v.defs))
	for name := range v.defs {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}

func (v *schemaValidator) validate(schema any, value any, path string, problems *[]string) {
	object, ok := schema.(map[string]any)
	if !ok {
		*problems = append(*problems, path+": schema node is not an object")
		return
	}
	for keyword := range object {
		if !supportedKeywords[keyword] {
			*problems = append(*problems, fmt.Sprintf("%s: schema uses the unsupported keyword %q", path, keyword))
			return
		}
	}

	if ref, ok := object["$ref"].(string); ok {
		target, found := v.resolve(ref)
		if !found {
			*problems = append(*problems, fmt.Sprintf("%s: schema $ref %q cannot be resolved", path, ref))
			return
		}
		v.validate(target, value, path, problems)
		return
	}

	if variants, ok := object["oneOf"].([]any); ok {
		v.validateVariants(variants, value, path, problems, true)
		return
	}
	if variants, ok := object["anyOf"].([]any); ok {
		v.validateVariants(variants, value, path, problems, false)
		return
	}
	if variants, ok := object["allOf"].([]any); ok {
		for _, variant := range variants {
			v.validate(variant, value, path, problems)
		}
		return
	}

	if rawType, ok := object["type"]; ok {
		if !typeMatches(rawType, value) {
			*problems = append(*problems, fmt.Sprintf("%s: expected %s, found %s", path, typeList(rawType), jsonTypeName(value)))
			return
		}
	}

	if rawEnum, ok := object["enum"].([]any); ok && !enumContains(rawEnum, value) {
		*problems = append(*problems, fmt.Sprintf("%s: %s is not one of %s", path, literal(value), literalList(rawEnum)))
		return
	}

	if format, ok := object["format"].(string); ok && format == "date-time" {
		text, isString := value.(string)
		if !isString {
			*problems = append(*problems, path+": format date-time expects a string")
			return
		}
		if _, err := time.Parse(time.RFC3339, text); err != nil {
			*problems = append(*problems, fmt.Sprintf("%s: %q is not an RFC3339 date-time", path, text))
			return
		}
	}

	if bounds, ok := value.(json.Number); ok {
		v.checkBounds(object, bounds, path, problems)
	}

	switch typed := value.(type) {
	case map[string]any:
		v.validateObject(object, typed, path, problems)
	case []any:
		v.validateArray(object, typed, path, problems)
	}
}

func (v *schemaValidator) validateVariants(variants []any, value any, path string, problems *[]string, exactlyOne bool) {
	matches := 0
	var firstFailure []string
	for _, variant := range variants {
		var local []string
		v.validate(variant, value, path, &local)
		if len(local) == 0 {
			matches++
			continue
		}
		if firstFailure == nil {
			firstFailure = local
		}
	}
	if matches == 0 {
		if firstFailure == nil {
			firstFailure = []string{path + ": no variant matched"}
		}
		*problems = append(*problems, append([]string{path + ": matches none of the schema variants"}, firstFailure...)...)
		return
	}
	if exactlyOne && matches > 1 {
		*problems = append(*problems, fmt.Sprintf("%s: matches %d schema variants, expected exactly one", path, matches))
	}
}

func (v *schemaValidator) validateObject(schema map[string]any, value map[string]any, path string, problems *[]string) {
	if required, ok := schema["required"].([]any); ok {
		for _, name := range required {
			key, isString := name.(string)
			if !isString {
				continue
			}
			if _, present := value[key]; !present {
				*problems = append(*problems, fmt.Sprintf("%s: required property %q is missing", path, key))
			}
		}
	}
	properties, _ := schema["properties"].(map[string]any)
	keys := make([]string, 0, len(value))
	for key := range value {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	for _, key := range keys {
		child := path + "." + key
		if property, known := properties[key]; known {
			v.validate(property, value[key], child, problems)
			continue
		}
		switch additional := schema["additionalProperties"].(type) {
		case nil:
		case bool:
			if !additional {
				*problems = append(*problems, fmt.Sprintf("%s: property %q is not declared by the schema", path, key))
			}
		case map[string]any:
			v.validate(additional, value[key], child, problems)
		}
	}
}

func (v *schemaValidator) validateArray(schema map[string]any, value []any, path string, problems *[]string) {
	if minimum, ok := schema["minItems"].(float64); ok && float64(len(value)) < minimum {
		*problems = append(*problems, fmt.Sprintf("%s: has %d items, minimum is %d", path, len(value), int(minimum)))
	}
	if maximum, ok := schema["maxItems"].(float64); ok && float64(len(value)) > maximum {
		*problems = append(*problems, fmt.Sprintf("%s: has %d items, maximum is %d", path, len(value), int(maximum)))
	}
	items, ok := schema["items"]
	if !ok {
		return
	}
	for i, element := range value {
		v.validate(items, element, fmt.Sprintf("%s[%d]", path, i), problems)
	}
}

func (v *schemaValidator) checkBounds(schema map[string]any, value json.Number, path string, problems *[]string) {
	number, err := value.Float64()
	if err != nil {
		*problems = append(*problems, fmt.Sprintf("%s: %s is not a number", path, value.String()))
		return
	}
	if minimum, ok := schema["minimum"].(float64); ok && number < minimum {
		*problems = append(*problems, fmt.Sprintf("%s: %v is below the minimum %v", path, number, minimum))
	}
	if maximum, ok := schema["maximum"].(float64); ok && number > maximum {
		*problems = append(*problems, fmt.Sprintf("%s: %v is above the maximum %v", path, number, maximum))
	}
}

func (v *schemaValidator) resolve(ref string) (any, bool) {
	const prefix = "#/$defs/"
	if !strings.HasPrefix(ref, prefix) {
		return nil, false
	}
	target, ok := v.defs[strings.TrimPrefix(ref, prefix)]
	return target, ok
}

// typeMatches implements the JSON Schema type test. json.Number is what the
// decoder produces with UseNumber, so the integer test is exact rather than
// dependent on a float round trip.
func typeMatches(rawType any, value any) bool {
	switch typed := rawType.(type) {
	case string:
		return matchesOneType(typed, value)
	case []any:
		for _, candidate := range typed {
			if name, ok := candidate.(string); ok && matchesOneType(name, value) {
				return true
			}
		}
		return false
	default:
		return false
	}
}

func matchesOneType(name string, value any) bool {
	switch name {
	case "null":
		return value == nil
	case "boolean":
		_, ok := value.(bool)
		return ok
	case "string":
		_, ok := value.(string)
		return ok
	case "number":
		_, ok := value.(json.Number)
		return ok
	case "integer":
		number, ok := value.(json.Number)
		if !ok {
			return false
		}
		parsed, err := number.Float64()
		return err == nil && math.Trunc(parsed) == parsed
	case "array":
		_, ok := value.([]any)
		return ok
	case "object":
		_, ok := value.(map[string]any)
		return ok
	default:
		return false
	}
}

func jsonTypeName(value any) string {
	switch typed := value.(type) {
	case nil:
		return "null"
	case bool:
		return "boolean"
	case string:
		return "string"
	case json.Number:
		if parsed, err := typed.Float64(); err == nil && math.Trunc(parsed) == parsed {
			return "integer"
		}
		return "number"
	case []any:
		return "array"
	case map[string]any:
		return "object"
	default:
		return reflect.TypeOf(value).String()
	}
}

func enumContains(allowed []any, value any) bool {
	for _, candidate := range allowed {
		if equalJSON(candidate, value) {
			return true
		}
	}
	return false
}

// equalJSON compares two decoded JSON values. The numbers in an enum and a
// document arrive as json.Number, so a string comparison of their renderings is
// not enough for the numeric case.
func equalJSON(a, b any) bool {
	numberA, okA := a.(json.Number)
	numberB, okB := b.(json.Number)
	if okA && okB {
		parsedA, errA := numberA.Float64()
		parsedB, errB := numberB.Float64()
		return errA == nil && errB == nil && parsedA == parsedB
	}
	return reflect.DeepEqual(a, b)
}

func literal(value any) string {
	return fmt.Sprintf("%v", value)
}

func literalList(values []any) string {
	parts := make([]string, 0, len(values))
	for _, value := range values {
		parts = append(parts, literal(value))
	}
	return strings.Join(parts, ", ")
}

func typeList(rawType any) string {
	switch typed := rawType.(type) {
	case string:
		return typed
	case []any:
		parts := make([]string, 0, len(typed))
		for _, candidate := range typed {
			parts = append(parts, literal(candidate))
		}
		return strings.Join(parts, " or ")
	default:
		return "unknown type"
	}
}
