package aggmodel

import (
	"encoding/json"
	"fmt"
	"reflect"
	"sort"
	"strings"
	"time"
)

// This file is the single source of truth for the artifact types. Every consumer
// reads the generated output, never a hand-written interface, so a change to an
// artifact shape shows up as a type error or a schema violation in whatever
// reads the tree instead of silently rendering blanks.
//
// Generation is reflection-based rather than code-generated from the Go AST,
// because the emitter has to run from `go run ./cmd/gen-types` inside a
// container with no toolchain beyond the compiler.

var timeType = reflect.TypeOf(time.Time{})

// enumRegistry maps the named string types that have a closed value set to
// that set. Adding a value is a contract change, so the registry is explicit
// rather than inferred: an inferred enum would silently widen the moment
// somebody added a constant.
var enumRegistry = map[reflect.Type][]string{
	reflect.TypeOf(Role("")):    roleStrings(),
	reflect.TypeOf(Tier("")):    tierStrings(),
	reflect.TypeOf(Bracket("")): bracketStrings(),
	reflect.TypeOf(Source("")):  sourceStrings(),
}

func sourceStrings() []string {
	return []string{string(SourceRiotMatchV5), string(SourceDemo)}
}

func roleStrings() []string {
	out := make([]string, 0, len(Roles))
	for _, r := range Roles {
		out = append(out, string(r))
	}
	return out
}

func tierStrings() []string {
	out := make([]string, 0, len(Tiers))
	for _, t := range Tiers {
		out = append(out, string(t))
	}
	return out
}

func bracketStrings() []string {
	// BracketAll is published; the rest are reserved. They are all in the
	// schema because a reader must accept a future artifact without a code
	// change, and a produced value outside this set is a build error.
	return []string{
		string(BracketAll),
		string(BracketEmeraldPlus),
		string(BracketPlatinumPlus),
		string(BracketDiamondPlus),
		string(BracketMasterPlus),
	}
}

// ArtifactRoots lists the document types the emitter publishes, in the order
// they appear in the generated output.
func ArtifactRoots() []any {
	return []any{
		TierList{},
		Champion{},
		Matchups{},
		Manifest{},
		StaticChampions{},
		StaticItems{},
		StaticRunes{},
		StaticSummonerSpells{},
		StaticPatches{},
	}
}

// SchemaDocumentID identifies the generated schema. It is a URL rather than a
// path so an editor or a validator can resolve it without a base directory.
const SchemaDocumentID = "https://github.com/Erik-Schuetze/league-of-legends/agg/v1/schema.json"

// Schema returns a JSON Schema 2020-12 document describing every artifact.
// The root accepts any one of the artifact types, because there is no single
// root: the tree holds several documents and validating "whichever this is" is
// the actual use.
func Schema() map[string]any {
	defs := map[string]any{}
	for _, t := range namedStructs() {
		defs[typeName(t)] = structSchema(t)
	}
	for _, t := range sortedEnumTypes() {
		defs[typeName(t)] = map[string]any{
			"type": "string",
			"enum": enumRegistry[t],
		}
	}

	oneOf := make([]any, 0, len(ArtifactRoots()))
	for _, root := range ArtifactRoots() {
		oneOf = append(oneOf, map[string]any{"$ref": "#/$defs/" + typeName(reflect.TypeOf(root))})
	}

	return map[string]any{
		"$schema": "https://json-schema.org/draft/2020-12/schema",
		"$id":     SchemaDocumentID,
		"title":   "League of Legends aggregate artifacts (agg/v1)",
		"oneOf":   oneOf,
		"$defs":   defs,
	}
}

// MarshalSchema renders Schema() as indented JSON with a trailing newline, so
// the checked-in file is stable across runs and diffs cleanly.
func MarshalSchema() ([]byte, error) {
	doc := Schema()
	buf, err := json.MarshalIndent(doc, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("marshal schema: %w", err)
	}
	return append(buf, '\n'), nil
}

// TypeScript renders the artifact types as an ambient module declaration. The
// output is written to schema/agg.d.ts by cmd/gen-types.
func TypeScript() string {
	var b strings.Builder

	b.WriteString("// Code generated by go run ./cmd/gen-types. DO NOT EDIT.\n")
	b.WriteString("// Source of truth: internal/aggmodel. Regenerate with `make types`.\n\n")

	for _, t := range sortedEnumTypes() {
		values := enumRegistry[t]
		quoted := make([]string, 0, len(values))
		for _, v := range values {
			quoted = append(quoted, fmt.Sprintf("%q", v))
		}
		fmt.Fprintf(&b, "export type %s = %s;\n\n", typeName(t), strings.Join(quoted, " | "))
	}

	for _, t := range namedStructs() {
		b.WriteString(tsInterface(t))
		b.WriteString("\n")
	}

	b.WriteString("// The artifact tree, relative to the aggregate root. Served under " + URLPrefix + ".\n")
	b.WriteString("export type ArtifactPath = string;\n\n")

	fmt.Fprintf(&b, "export declare const SCHEMA_VERSION: %d;\n", SchemaVersion)
	fmt.Fprintf(&b, "export declare const QUEUE_RANKED_SOLO_5X5: %d;\n", QueueIDRankedSolo5x5)

	return b.String()
}

func tsInterface(t reflect.Type) string {
	var b strings.Builder

	base, own := embeddedAndOwnFields(t)

	fmt.Fprintf(&b, "export interface %s", typeName(t))
	if len(base) > 0 {
		fmt.Fprintf(&b, " extends %s", strings.Join(base, ", "))
	}
	b.WriteString(" {\n")

	for _, f := range own {
		name, optional, _ := jsonField(f)
		fmt.Fprintf(&b, "  %s%s: %s;\n", name, optionalMark(optional), tsType(f.Type))
	}

	b.WriteString("}\n")
	return b.String()
}

func optionalMark(optional bool) string {
	if optional {
		return "?"
	}
	return ""
}

func tsType(t reflect.Type) string {
	switch t.Kind() {
	case reflect.Pointer:
		return tsType(t.Elem())
	case reflect.Bool:
		return "boolean"
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64,
		reflect.Float32, reflect.Float64:
		return "number"
	case reflect.String:
		if _, ok := enumRegistry[t]; ok {
			return typeName(t)
		}
		return "string"
	case reflect.Slice, reflect.Array:
		// A Go slice always marshals to a JSON array, never to null, but a
		// nil slice marshals to `[]` only because the producers initialise
		// them. The type stays non-nullable so a producer that forgets is a
		// visible bug rather than a silently accepted null.
		return tsType(t.Elem()) + "[]"
	case reflect.Map:
		return "Record<string, " + tsType(t.Elem()) + ">"
	case reflect.Struct:
		if t == timeType {
			return "string"
		}
		return typeName(t)
	default:
		return "unknown"
	}
}

func structSchema(t reflect.Type) map[string]any {
	_, own := embeddedAndOwnFields(t)

	props := map[string]any{}
	required := make([]string, 0, len(own))

	// Embedded structs are inlined rather than expressed with allOf: allOf
	// against a base that sets additionalProperties:false would reject every
	// field the derived type adds, which is a well-known footgun and not one
	// worth walking into for a schema this small.
	for _, f := range embeddedFields(t) {
		inlined := structSchema(f.Type)
		for k, v := range inlined["properties"].(map[string]any) {
			props[k] = v
		}
		if names, isList := inlined["required"].([]string); isList {
			required = append(required, names...)
		}
	}

	for _, f := range own {
		name, optional, _ := jsonField(f)
		props[name] = jsonSchemaFor(f.Type)
		if !optional {
			required = append(required, name)
		}
	}

	out := map[string]any{
		"type":                 "object",
		"properties":           props,
		"additionalProperties": false,
	}
	if len(required) > 0 {
		out["required"] = required
	}
	return out
}

func jsonSchemaFor(t reflect.Type) map[string]any {
	switch t.Kind() {
	case reflect.Pointer:
		return jsonSchemaFor(t.Elem())
	case reflect.Bool:
		return map[string]any{"type": "boolean"}
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64:
		return map[string]any{"type": "integer"}
	case reflect.Float32, reflect.Float64:
		return map[string]any{"type": "number"}
	case reflect.String:
		if _, ok := enumRegistry[t]; ok {
			return map[string]any{"$ref": "#/$defs/" + typeName(t)}
		}
		return map[string]any{"type": "string"}
	case reflect.Slice, reflect.Array:
		return map[string]any{"type": "array", "items": jsonSchemaFor(t.Elem())}
	case reflect.Map:
		return map[string]any{"type": "object", "additionalProperties": jsonSchemaFor(t.Elem())}
	case reflect.Struct:
		if t == timeType {
			return map[string]any{"type": "string", "format": "date-time"}
		}
		return map[string]any{"$ref": "#/$defs/" + typeName(t)}
	default:
		return map[string]any{}
	}
}

// embeddedAndOwnFields splits a struct into the anonymous struct fields that
// become the TypeScript base and the ordinary fields that become its own
// members.
func embeddedAndOwnFields(t reflect.Type) ([]string, []reflect.StructField) {
	var base []string
	for _, f := range embeddedFields(t) {
		base = append(base, typeName(f.Type))
	}
	return base, ownFields(t)
}

func embeddedFields(t reflect.Type) []reflect.StructField {
	var out []reflect.StructField
	for i := 0; i < t.NumField(); i++ {
		f := t.Field(i)
		if f.Anonymous && f.Type.Kind() == reflect.Struct && f.Type != timeType {
			out = append(out, f)
		}
	}
	return out
}

func ownFields(t reflect.Type) []reflect.StructField {
	var out []reflect.StructField
	for i := 0; i < t.NumField(); i++ {
		f := t.Field(i)
		if f.Anonymous || !f.IsExported() {
			continue
		}
		if _, _, ok := jsonField(f); !ok {
			continue
		}
		out = append(out, f)
	}
	return out
}

// jsonField returns the JSON name for a field, whether it is optional, and
// whether the field participates at all.
func jsonField(f reflect.StructField) (name string, optional bool, ok bool) {
	tag := f.Tag.Get("json")
	if tag == "-" {
		return "", false, false
	}
	parts := strings.Split(tag, ",")
	name = parts[0]
	if name == "" {
		name = f.Name
	}
	for _, opt := range parts[1:] {
		if opt == "omitempty" {
			optional = true
		}
	}
	return name, optional, true
}

func typeName(t reflect.Type) string {
	if t.Name() == "" {
		return "Anonymous"
	}
	return t.Name()
}

// namedStructs walks the roots depth-first in field order so the generated
// output is byte-stable across runs. A map iteration here would produce a
// diff on every regeneration.
func namedStructs() []reflect.Type {
	var order []reflect.Type
	seen := map[reflect.Type]bool{}

	var visit func(t reflect.Type)
	visit = func(t reflect.Type) {
		switch t.Kind() {
		case reflect.Pointer, reflect.Slice, reflect.Array, reflect.Map:
			visit(t.Elem())
		case reflect.Struct:
			if t == timeType || seen[t] {
				return
			}
			seen[t] = true
			order = append(order, t)
			for i := 0; i < t.NumField(); i++ {
				visit(t.Field(i).Type)
			}
		}
	}

	for _, root := range ArtifactRoots() {
		visit(reflect.TypeOf(root))
	}
	return order
}

func sortedEnumTypes() []reflect.Type {
	types := make([]reflect.Type, 0, len(enumRegistry))
	for t := range enumRegistry {
		types = append(types, t)
	}
	sort.Slice(types, func(i, j int) bool { return typeName(types[i]) < typeName(types[j]) })
	return types
}
