/**
 * The aggregate artifact contract, as generated by `make types`.
 *
 * `schema/agg.d.ts` is authoritative: it is emitted from `internal/aggmodel`,
 * the same source of truth the pipeline is written against. The mockup imports
 * the contract through this one name rather than redeclaring any of it, because
 * a second hand-written copy drifts, and it drifts silently.
 *
 * Type-only, so nothing here survives to runtime and no bundler resolution is
 * involved. The relative path reaches the repository root because the mockup is
 * a self-contained review app that has no build-time relationship with the
 * pipeline.
 */
export type * from "../../../../../schema/agg";
