// Code generated by go run ./cmd/gen-types. DO NOT EDIT.
// Source of truth: internal/aggmodel. Regenerate with `make types`.

export type Bracket = "all" | "emerald_plus" | "platinum_plus" | "diamond_plus" | "master_plus";

export type Role = "TOP" | "JUNGLE" | "MID" | "BOTTOM" | "SUPPORT";

export type Source = "riot-match-v5" | "demo";

export type Tier = "S+" | "S" | "A" | "B" | "C" | "D";

export interface TierList extends Envelope {
  cells: Cell[];
}

export interface Envelope {
  schema: number;
  source: Source;
  patch: string;
  region: string;
  queue: number;
  bracket: Bracket;
  generated_at: string;
  source_window: Window;
  min_cell_n: number;
  suppressed_cells: number;
}

export interface Window {
  from: string;
  to: string;
}

export interface Cell {
  champion_id: number;
  role: Role;
  n: number;
  wins: number;
  win_rate: number;
  pick_rate: number;
  ban_rate: number;
  tier: Tier;
  ci95_half_width: number;
}

export interface Champion extends Envelope {
  champion_id: number;
  champion_slug: string;
  roles: ChampionRole[];
}

export interface ChampionRole {
  role: Role;
  stats: Cell;
  items: Build[];
  runes: Build[];
  spells: Build[];
  skill_orders: SkillOrder[];
}

export interface Build {
  kind: string;
  key: number[];
  label: string;
  n: number;
  wins: number;
  win_rate: number;
}

export interface SkillOrder {
  order: string;
  n: number;
  wins: number;
  win_rate: number;
}

export interface Matchups extends Envelope {
  role: Role;
  champions: number[];
  cells: MatchupCell[];
}

export interface MatchupCell {
  champion_id: number;
  opponent_id: number;
  n: number;
  wins: number;
  win_rate: number;
  ci95_half_width: number;
}

export interface Manifest {
  schema: number;
  source: Source;
  generated_at: string;
  latest: Partition;
  partitions: Partition[];
}

export interface Partition {
  patch: string;
  region: string;
  queue: number;
  bracket: Bracket;
  generated_at: string;
  source_window: Window;
  min_cell_n: number;
  suppressed_cells: number;
  cells_published: number;
  build_run_id: number;
  git_sha: string;
  champions: number[];
  matchup_roles: Role[];
}

export interface StaticChampions {
  ddragon_version: string;
  champions: StaticChampion[];
}

export interface StaticChampion {
  id: number;
  key: string;
  slug: string;
  name: string;
  icon: string;
  roles: Role[];
}

export interface StaticItems {
  ddragon_version: string;
  items: StaticItem[];
}

export interface StaticItem {
  id: number;
  name: string;
  icon: string;
}

export interface StaticRunes {
  ddragon_version: string;
  runes: StaticRune[];
}

export interface StaticRune {
  id: number;
  name: string;
  icon: string;
  tree: number;
}

export interface StaticSummonerSpells {
  ddragon_version: string;
  spells: StaticSummonerSpell[];
}

export interface StaticSummonerSpell {
  id: number;
  name: string;
  icon: string;
}

export interface StaticPatches {
  ddragon_version: string;
  latest: string;
  patches: string[];
}

// The artifact tree, relative to the aggregate root. Served under /agg.
export type ArtifactPath = string;

export declare const SCHEMA_VERSION: 1;
export declare const QUEUE_RANKED_SOLO_5X5: 420;
